Design
GhislainMitahi/gm-math-magiciens pull request #2
Opened 2022-09-08 15:21 UTC by GhislainMitahi

### INIT INTERFACE

In this stage I did :

- Deleted all the boilerplate from CRA (text, images, styles).

- Created a directory called components.

- Inside components, I created a new Calculator.js file.

- In Calculator.js, create a React component that matches the design

2022-09-08 15:48 UTC, CollinsTatang requested changes
Hi @GhislainMitahi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-08 15:48 UTC, CollinsTatang commented on src/components/calculator.js
> +  // eslint-disable-next-line no-useless-constructor
- [ ] Please do not disable the linters rather fix them to make your code clean and easy to maintain.

2022-09-08 17:40 UTC, aimemalaika approved these changes
Hi @GhislainMitahi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-10 09:25 UTC, merged

2023-06-17 14:46 UTC, GhislainMitahi commented on src/components/calculator.js
> +  // eslint-disable-next-line no-useless-constructor
Good, let me work on it

2023-06-17 14:47 UTC, GhislainMitahi commented
Good, this motivates me for sure !